// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// tanimoto_cpp
arma::mat tanimoto_cpp(const arma::mat& X, const arma::mat& Y);
RcppExport SEXP _SCORPION_tanimoto_cpp(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(tanimoto_cpp(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// normalize_rows_cpp
arma::mat normalize_rows_cpp(const arma::mat& X);
RcppExport SEXP _SCORPION_normalize_rows_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(normalize_rows_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// update_diagonal_cpp
arma::mat update_diagonal_cpp(arma::mat X, int n, double alpha, int step);
RcppExport SEXP _SCORPION_update_diagonal_cpp(SEXP XSEXP, SEXP nSEXP, SEXP alphaSEXP, SEXP stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    rcpp_result_gen = Rcpp::wrap(update_diagonal_cpp(X, n, alpha, step));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SCORPION_tanimoto_cpp", (DL_FUNC) &_SCORPION_tanimoto_cpp, 2},
    {"_SCORPION_normalize_rows_cpp", (DL_FUNC) &_SCORPION_normalize_rows_cpp, 1},
    {"_SCORPION_update_diagonal_cpp", (DL_FUNC) &_SCORPION_update_diagonal_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SCORPION(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
