# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast Tanimoto similarity computation using RcppArmadillo
#' @param X First matrix (rows: features, cols: samples)
#' @param Y Second matrix (rows: samples, cols: features)
#' @return Tanimoto similarity matrix
#' @noRd
tanimoto_cpp <- function(X, Y) {
    .Call(`_SCORPION_tanimoto_cpp`, X, Y)
}

#' Fast matrix normalization
#' @param X Input matrix
#' @return Normalized matrix with mean 0 and unit L2 norm per row
#' @noRd
normalize_rows_cpp <- function(X) {
    .Call(`_SCORPION_normalize_rows_cpp`, X)
}

#' Update diagonal elements during PANDA iteration
#' @param X Input matrix
#' @param n Dimension
#' @param alpha Learning rate
#' @param step Current iteration step
#' @return Matrix with updated diagonal
#' @noRd
update_diagonal_cpp <- function(X, n, alpha, step) {
    .Call(`_SCORPION_update_diagonal_cpp`, X, n, alpha, step)
}

